kinara_capital_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from student_grid.views import StudentListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', StudentListView.as_view(), name='default-page'),
    path('student/', include('student_grid.urls', namespace='student_grid'), name="student_grid"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # to display images on web pages

student_grid/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
# from django.views.i18n import JavaScriptCatalog

app_name='student_grid'

urlpatterns = [
    path("", views.StudentListView.as_view(), name="student_list")
]

student_grid/models.py
from django.db import models
from django.contrib import auth
from django.urls import reverse
from django.utils import timezone
# Create your models here.

class Student(models.Model):
    gender_choices = (
        ('Male','Male'),
        ('Female','Female')
        )
    
    std_id = models.CharField(max_length=15, verbose_name="Student ID", unique=True)
    std_fname = models.CharField(max_length=50, verbose_name="First Name")
    std_lname = models.CharField(max_length=50, verbose_name="Last Name", default=None)
    dob = models.DateField(auto_now=False, auto_now_add=False, verbose_name="Date of Birth")
    gender = models.CharField(verbose_name="Gender", choices=gender_choices, default='Male', max_length=10)
    max_total_marks = models.CharField(max_length=4, verbose_name="Maximum Total Marks")
    total_marks = models.CharField(max_length=4, verbose_name="Gained Total Marks")
    percentage = models.CharField(max_length=3, verbose_name="Percentage")

    REQUIRED_FIELDS = ['std_id','std_fname','dob','gender', 'max_total_marks','total_marks','percentage']

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"

    def __str__(self):
        return self.std_id

    # def get_absolute_url(self):
    #     return reverse("Student_detail", kwargs={"pk": self.pk})

kinara_capital_assignment/views.py
from django.views.generic import TemplateView
from django.shortcuts import render

def default_view(request):
    return render(request, 'index.html')

class Homepage(TemplateView):
    template_name='index.html'

student_grid/views.py
from django.shortcuts import render
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView)
from django.utils import timezone
from django.urls import reverse_lazy
from django.core.paginator import Paginator

# models
from student_grid.models import Student

class StudentListView(ListView):
    model = Student
    template_name = "index.html"
    queryset = Student.objects.all()
    context_object_name = 'student_list'
    paginate_by = 10

    def get_paginate_by(self, queryset):
        num_records = self.request.GET.get('no_of_rows')
        if num_records:
            print("Hi")
            try:
                return int(num_records)
            except ValueError:
                pass

        return self.paginate_by
    
    def get_queryset(self):
        # queryset = super().get_queryset()
        student_id = self.request.GET.get('student_id')
        fname = self.request.GET.get('fname')
        lname = self.request.GET.get('lname')
        gender = self.request.GET.get('gender')
        minpercentage = self.request.GET.get('minpercentage')
        maxpercentage = self.request.GET.get('maxpercentage')
        # self.paginate_by = self.request.GET.get('no_of_rows')

        if student_id:
            self.queryset = self.queryset.filter(std_id=student_id)

        if fname:
            self.queryset = self.queryset.filter(std_fname__icontains=fname)
        
        if lname:
            self.queryset = self.queryset.filter(std_lname__icontains=lname)
        
        if gender:
            self.queryset = self.queryset.filter(gender=gender)
        
        if minpercentage:
            self.queryset = self.queryset.filter(percentage__gt=minpercentage)
        
        if maxpercentage:
            self.queryset = self.queryset.filter(percentage__lt=maxpercentage)

        return self.queryset
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     paginator = Paginator(context['student_list'], self.paginate_by)
    #     page_number = self.request.GET.get('page')
    #     page_obj = paginator.get_page(page_number)
    #     context['page_obj'] = page_obj
    #     return context

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <title> Meeting Scheduler </title>
            {% comment %} bootstrap jquery link {% endcomment %}
            <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
            <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

            {% comment %} Bootstrap {% endcomment %}
            <!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>    
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

            <!-- Optional theme -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

            <!-- Latest compiled and minified JavaScript -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

            {% comment %} Medium Stype Editor {% endcomment %}
            <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
            <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

            {% comment %} custom css {% endcomment %}
            {% comment %} <link rel = "stylesheet" href="{% static 'problem_solvers_centre/css/master.css' %}"> {% endcomment %}
            <link rel = "stylesheet" href="{% static 'master.css' %}">

            {% comment %} Fonts {% endcomment %}
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&family=Russo+One&display=swap" rel="stylesheet">
            <link rel="preconnect" href="https://fonts.googleapis.com">
            
            {% comment %} font Oswald {% endcomment %}
            <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">

            <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
            <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
            <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script> 
    </head>

    <body>

        <nav class="navbar navbar-default fixed-top techfont custom-navbar" >
            <div class= "container">
                    {% comment %} anything we put in the navbar will be contained by the container {% endcomment %}
                <ul class="nav navbar-nav">
                    <li> <a href=""> <span class="glyphicon-bold text-success"> Student Grid System </span> </a> </li>
                </ul>
            </div>
        </nav>


        <div class="container"> 
            {% block content %}

            {% endblock content %}
        </div>

    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    <div class="container student-details">
        <div class="" style="padding-top:80px;"> 
            <div class="container">
                <h1 style="font-family: 'Russo One',sans-serif;">Apply Filter</h1>
                <form method="GET" action="{% url 'student_grid:student_list' %}" class="filter">
                    <table>
                        <tr>
                            <td style="padding-right:150px;">
                                <div class="form-group">
                                    <label>Student ID: </label><br>
                                    <input type="text" name="student_id" placeholder="Student ID">
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <label>First Name: </label><br>
                                    <input type="text" name="fname" placeholder="First Name">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label>Last Name: </label><br>
                                    <input type="text" name="lname" placeholder="Last Name">
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <label>Gender: </label>
                                    <select name="gender">
                                        <option value="">Select Gender</option>
                                        <option value="Male"> Male</option>
                                        <option value="Female">Female</option>
                                      </select>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label>Minimum Percentage: </label><br>
                                    <input type="text" name="minpercentage" placeholder="Minimum Percentage">
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <label>Number of records per page: </label>
                                    <select name="no_of_rows">
                                        <option value="5" selected> 5 </option>
                                        <option value="10"> 10 </option>
                                        <option value="15"> 15 </option>
                                        <option value="20"> 20 </option>
                                        <option value="30"> 30 </option>
                                        <option value="50"> 50 </option>
                                      </select>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <button type="submit" class="btn btn-primary">Fetch details</button>
                </form>
            </div>

            <div class="t-row1" style="display:flex; flex-direction:row; padding-top:40px;" >  
                <table class="table table-hover table-striped table-bordered thead-dark">
                    <thead class="bg-blue">
                        <tr>
                            <th>Student ID</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Date of Birth</th>
                            <th>Gender</th>
                            <th>Maximum Total Marks</th>
                            <th>Gained Total Marks</th>
                            <th>Percentage</th>
                          </tr>
                    </thead>
                    <tbody>
                        {% for student in page_obj %}
                        <tr>
                            <td>{{ student.std_id }}</td>
                            <td>{{ student.std_fname }}</td>
                            <td>{{ student.std_lname }}</td>
                            <td>{{ student.dob }}</td>
                            <td>{{ student.gender }}</td>
                            <td>{{ student.max_total_marks }}</td>
                            <td>{{ student.total_marks }}</td>
                            <td>{{ student.percentage }}</td>
                          </tr>
                          {%empty%}
                          <td colspan="8">No student details are available!</td>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="pagination-bar">
                {% comment %} pagination {% endcomment %}
              <nav aria-label="Pagination" style="text-align:center;">
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a>
                  </li>
                  {% endif %}
              
                  {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                  <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
                  </li>
                  {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                  </li>
                  {% endif %}
                  {% endfor %}
              
                  {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Next</span>
                    </a>
                  </li>
                  {% endif %}
                </ul>
              </nav>
              {% comment %} end pagination {% endcomment %}
            </div>
        </div>
    </div>
{% endblock content %}